drop schema public cascade;

drop table uzytkownik if exists;
create table uzytkownik (
                            id integer generated by default as identity primary key,
                            login varchar(50) not null unique,
                            haslo varchar(100) not null,
                            email varchar(100) not null unique,
                            data_rejestracji timestamp default current_timestamp
);

drop table follower if exists;
create table follower (
                          id integer generated by default as identity primary key,
                          uzytkownik_id integer not null,
                          follower_id integer not null,
                          data_dodania timestamp default current_timestamp,
                          foreign key (uzytkownik_id) references uzytkownik(id) on delete cascade,
                          foreign key (follower_id) references uzytkownik(id) on delete cascade,
                          unique (uzytkownik_id, follower_id)
);

drop table wpis if exists;
create table wpis (
                      id integer generated by default as identity primary key,
                      uzytkownik_id integer not null,
                      tresc varchar(280) not null,
                      data_utworzenia timestamp default current_timestamp,
                      foreign key (uzytkownik_id) references uzytkownik(id) on delete cascade
);